language: python

python:
  - "2.7"
  #- "3.4"
  - "pypy"
  #- "pypy3"

install:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="4.0.1"
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source devp2p setup.py test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: ethereum_pypi_automated
  password:
    secure: "CoLY2r4vgY1kvJdd824hpEjmkxzs9uf2lapQNUaGB3sRytOLRAF3cfA924WFeKwp1ZVsXwKEp0ZvoLQ26JB2JqThrP7vjR24tSSN+tTkBL9h4eoHCA+W3CX+FFFHMxL6t9VCYjXHQvk/cm3zubVx/e4x1pi4WFlJCYgXY5nnStI="
  on:
    tags: true
    repo: ethereum/pydevp2p
    branch: develop
  distributions: "sdist bdist_wheel"
